




/* This has been submitted before as a project on Program Pool. This is a further
   modification to the program as referenced to improvement from the original author
   of the software. */




   
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include <ctype.h>

#define ARR_LEN 24
#define SHIFT 10

/* This function will declare a swap value (hence swapValue) which will interchange
   with firstValue and secondValue to shuffle the array. */
void swap(char *firstValue, char *secondValue) {
    char swapValue = *firstValue;
    *firstValue = *secondValue;
    *secondValue = swapValue;
}

/* Generate a random sequence of an array. */
void randomize(char charArr[], int n) {
    srand (time(NULL)); /* Prevent the program from generating duplicate values. */
    /* Swap each element one-by-one, excluding the 1st element. */
    for (int i = n - 1; i > 0; i--) {
        int j = rand() % (i + 1);
        swap(&charArr[i], &charArr[j]);
    }
}

void exportPass(char passArr[], int passLen) {
    FILE *exportData = fopen("passwordOutput.txt", "w");
    for (int i = 0; i < passLen; i++) {
        fprintf(exportData, "%c", passArr[i]);
    }
}

/* Function for encrypting the string generated by "randomize". */
int encryptData(char passArr[], char charArr[], int passLen) {
    int willEncrypt;
    printf("\nWould you like to encrypt your password? Enter 1 for YES, 2 for NO :: ");
    scanf("%d", &willEncrypt);
    if (willEncrypt == 1) {
        for (int i = 0; i < passLen; i++) {
            passArr[i] = charArr[i + SHIFT];
            printf("%c", passArr[i]);
        }
        exportPass(passArr, passLen); 
        printf("\nThank you for using the Random Password Generator, check output.txt for your password.\n");
    }
    else if (willEncrypt == 2) {
        exportPass(passArr, passLen);
        system("clear");
        printf("Thank you for using the Random Password Generator, check output.txt for your password.\n");
        sleep(2);
        system("exit");
    }
    else {
        printf("Error: Please enter a character that satisfies the requirements.\n");
        encryptData(passArr, charArr, passLen);
    }
}

/* Primary function that calls to other functions in order to make the core program work. */
int main() {
    int passLen;
    char passArr[ARR_LEN];
    char charArr[] = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$^&*()[]?";
    int n = sizeof(charArr) / sizeof(charArr[0]);
    randomize (charArr, n);
    printf("How many characters, between 8 and 24, would you like to generate? :: ");
    scanf("%d", &passLen);
    if (passLen <= 24 || passLen >= 8) {
        printf("Password: ");
        for (int i = 0; i < passLen; i++) {
            passArr[i] = charArr[i];
            printf("%c", passArr[i]);
        }
        encryptData(passArr, charArr, passLen);
    }
    else {
        system("clear");
        printf("Error: Please enter a character that satisfies the requirements.\n");
        main();
    }
    return 0;
}

// extra; handle file properties - e.g. add a chosen password to the password file